
 <footer class="index_footer" aria-label="external links">
    <p><a href="mailto:someone@example.com">Send email</a></p>
    <p><a href="https://jack-rosewarne.atlassian.net/jira/software/projects/AWPP1/boards/34">Jira Link</a></p>
    <p><a href="https://github.com/DaveyJonesLockerroom/Group-1---Web-Project---SDAJ">Github Link</a></p>
</footer>

<p class= "index_footer_caption" style="
    text-align: center; 
    border: 0.2px solid gold; border-radius: 4px; 
    background-color: black; 
    margin-top: 20px; max-width: 500px; 
    margin-left: auto; 
    margin-right: auto;
">
    &copy; 2025 Swinburne University of Technology 
</p>