<?php 
session_start();
include_once __DIR__ .'/env.loader.php';

$host = getenv('DB_HOST');
$user = getenv('DB_USER');
$password = getenv('DB_PASSWORD');
$db = getenv('DB_NAME');

$conn = mysqli_connect($host, $user, $password, $db);

if (!$conn) {#check the sytanx for this
          echo "<p> Connection to database failed: " . mysqli_connect_error() . "</p>";
}
?>

<!--Code structure referencing for above: 
W3Schools. (n.d.). PHP Connect to MySQL. W3Schools.com. https://www.w3schools.com/php/php_mysql_connect.asp --->


<!DOCTYPE html>
<html lang="en">

<head>
    <?php include 'header.inc'; ?>
    <!-- Preload logo image -->
    <link rel="preload" as="image" href="images/company_logo.png">
</head>

<body>
    <!-- Navigation bar -->
    <?php include 'navbar.inc'; ?>

    <main class="main-content">
        <!-- Page heading -->
        <h1 class="main-title">JOB OPENINGS</h1>

        <!-- Intro paragraph -->
        <p id="intro">
            Here at SDAJ, we are looking for a number of dedicated individuals to support us in our journey of
            creating some of the best games in the world.
        </p>

        <!-- Section with UL and ASIDE -->
        <section class="benefits-wrap" aria-labelledby="benefits-title">
            <!-- Unordered list: Benefits -->
            <div class="benefits">
                <h2 id="benefits-title">Why Work With Us?</h2>
                <ul>
                    <li>Collaborative and creative team environment</li>
                    <li>Opportunities to work on high level projects</li>
                    <li>Flexible work hours and remote options</li>
                    <li>Comprehensive health and wellness programs</li>
                    <li>Competitive salary and benefits package</li>
                    <li>Professional development and growth opportunities</li>
                    <li>Inclusive and diverse workplace culture</li>
                </ul>
            </div>

            <!-- Game promo box -->
            <aside class="game-promo" aria-labelledby="aside-title">
                <h2 id="aside-title">🎮 Join Our Game Dev Team!</h2>
                <p>We're building a pixel-style RPG set in a fractured kingdom. Apply now to shape the world,
                    mechanics, and lore!</p>
                <img src="images/game-preview.png" alt="Game preview image"> <!-- Image Generated by deepai.org  -->
            </aside>
        </section>

        <!-- Table  -->
        <section aria-labelledby="jobs-title" class="jobs-section">
            <h2 id="jobs-title" class="table-title">Job Listings</h2>
            <div class="table-wrap">
                    <table id="job-listings">
                        <caption class="table-title">Available job openings at SDAJ</caption>
                        <tr>
                            <th class="ref-column">Reference Number</th>
                            <th class="title-column">Job Title - Salary</th>
                            <th class="desc-column">Description</th>
                            <th class="resp-column">Responsibilities & Requirements</th>
                        </tr>
                        <tr>
                            <td>LP032</td>
                            <td>Lead Game Programmer - $120,000 - $150,000</td>
                            <td>Oversees the programming team and ensures code quality and performance.
                             <br> <br>
                            <strong>Reports to:</strong> Game Director</td>

                            <td>
                                <h4>Responsibilities</h4>
                                <ul>
                                    <li>Develop ideas and gameplay systems that fit the overall design of projects.</li>
                                    <li>Create engaging level designs, puzzles, and mechanics for 2D environments.</li>
                                    <li>Work closely with programmers and artists to ensure the design vision is faithfully executed.</li>
                                </ul>

                                <h4>Essential Requirements</h4>
                                <ul>
                                    <li>5+ years experience in game design or interactive media.</li>
                                    <li>Proficiency with mainstream design tools such as Unity, Unreal Engine</li>
                                    <li>Strong understanding of gameplay flow, pacing, and player engagement.</li>
                                </ul>

                                <h4>Preferable Skills</h4>
                                <ul>
                                    <li>Experience in tile-based level editors or retro game mechanics design.</li>
                                    <li>Experience with leading a team and project management.</li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>GD045</td>
                            <td>Game Designer - $90,000 - $110,000</td>
                            <td>Responsible for designing the core mechanics of our games.
                                <br> <br>
                            <strong>Reports to:</strong> Lead Game Designer.
                            </td>
                            <td>
                                <h4>Responsibilities</h4>
                                <ul>
                                    <li>Create engaging level designs, puzzles, and mechanics for 2D environments.</li>
                                    <li>Develop ideas that keep the experience challening, while still fair.</li>
                                </ul>

                                <h4>Essential Requirements</h4>
                                <ul>
                                    <li>2+ years experience in game design</li>
                                    <li>Proficiency with design tools such as Unity, Unreal Engine, or Godot.</li>
                                    <li>Willing to work well with a team and take constructive criticism.</li>
                                </ul>

                                <h4>Preferable Skills</h4>
                                <ul>
                                    <li>Experience in tile-based level editors or retro game mechanics design.</li>
                                    <li>Knowledge of classic game genres: platformers, beat ’em ups, and RPGs.</li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>AR058</td>
                            <td>2D Artist - $80,000 - $95,000</td>
                            <td>Create 2D models and animations for our games.
                                <br> <br>
                            <strong>Reports to:</strong> Art Director.
                            </td>
                            <td>
                                <h4>Responsibilities</h4>
                                <ul>
                                    <li>Create concept art and character designs that fit the game’s aesthetic.</li>
                                    <li>Produce high-quality 2D assets including sprites, backgrounds, and UI elements.</li>
                                    <li>Collaborate with designers and programmers to ensure art assets are implemented correctly.</li>
                                </ul>
                                <h4>Essential Requirements</h4>
                                <ul>
                                    <li>2+ years experience in 2D art and animation.</li>
                                    <li>Proficiency with graphic design software such as Adobe Photoshop, Illustrator, or similar tools.</li>
                                </ul>

                                <h4>Preferable Skills</h4>
                                <ul>
                                    <li>Experience with pixel art and animation techniques.</li>
                                    <li>Knowledge of game development pipelines and asset optimization.</li>
                                </ul>
                            </td>
                            
                            
                        </tr>
                    </table>
            </div>
        </section>

        <!-- Ordered list: Hiring process -->
        <section class="hiring-process" aria-labelledby="process-title">
            <h2 id="process-title">Our Hiring Process</h2>
            <ol>
                <li>Submit your application online</li>
                <li>Initial HR screening call</li>
                <li>Technical/creative interview</li>
                <li>Final team interview</li>
                <li>Receive your offer and join SDAJ!</li>
            </ol>
        </section>

        <!-- Application link -->
        <div class="application">
            <p><a href="apply.php" target="_blank">Apply Here</a></p>
        </div>
    </main>

    <!-- Footer -->
    <?php include 'footer.inc'; ?>
    
    
</body>
</html>
