<?php 
session_start();

include_once 'env_loader.php';
include_once 'conn.php';


if (!$conn) {
          die("<p> We are experiencing technical difficulties, please try again later</p>");
}
?>


<!--Code structure referencing for above: 
W3Schools. (n.d.). PHP Connect to MySQL. W3Schools.com. https://www.w3schools.com/php/php_mysql_connect.asp --->


<!DOCTYPE html>
<html lang="en">

<head>
    <?php include 'inc_files/header.inc'; ?>
    <!-- Preload logo image -->
    <link rel="preload" as="image" href="images/company_logo.png">
</head>

<body>
    <!-- Navigation bar -->
    <?php include 'inc_files/navbar.inc'; ?>

    <main class="main-content">
        <!-- Page heading -->
        <h1 class="main-title">JOB OPENINGS</h1>

        <!-- Intro paragraph -->
        <p id="intro">
            Here at SDAJ, we are looking for a number of dedicated individuals to support us in our journey of
            creating some of the best games in the world.
        </p>

        <!-- Section with UL and ASIDE -->
        <section class="benefits-wrap" aria-labelledby="benefits-title">
            <!-- Unordered list: Benefits -->
            <div class="benefits">
                <h2 id="benefits-title">Why Work With Us?</h2>
                <ul>
                    <li>Collaborative and creative team environment</li>
                    <li>Opportunities to work on high level projects</li>
                    <li>Flexible work hours and remote options</li>
                    <li>Comprehensive health and wellness programs</li>
                    <li>Competitive salary and benefits package</li>
                    <li>Professional development and growth opportunities</li>
                    <li>Inclusive and diverse workplace culture</li>
                </ul>
            </div>

            <!-- Game promo box -->
            <aside class="game-promo" aria-labelledby="aside-title">
                <h2 id="aside-title">🎮 Join Our Game Dev Team!</h2>
                <p>We're building a pixel-style RPG set in a fractured kingdom. Apply now to shape the world,
                    mechanics, and lore!</p>
                <img src="images/game-preview.png" alt="Game preview image"> <!-- Image Generated by deepai.org  -->
            </aside>
        </section>

        <!-- Table  -->
        <section aria-labelledby="jobs-title" class="jobs-section">
            <h2 id="jobs-title" class="table-title">Job Listings</h2>
        
            <?php 

                $stmt = $conn->prepare('SELECT * FROM `jobs`'); 
                $stmt->execute();
                $result = $stmt->get_result();

                if (mysqli_num_rows($result) > 0) { /* checks if there are results from the quiery */
                    echo "<table class='jobs_listings' aria-label = 'jobs listing for gaming development company'>"; #ARIA accessibility 
                    echo "<thead>";
                    echo "<tr><th>Reference Number</th><th>Job Title/Salary</th><th>Description</th><th>Responsibilites & Requirements</th></tr>";
                    echo "</thead><tbody>";

                    while ($row = mysqli_fetch_assoc($result)) { /* fetches associated  array */
                        echo "<tr>";
                        echo "<td class='ref_number'>" . htmlspecialchars($row['reference_number']) . "</td>"; /* htmlspecialchars to prevent XSS attacks */
                        echo "<td class='job_title'>" . nl2br(htmlspecialchars($row['Job Title/Salary'])) . "</td>";
                        echo "<td class='description'>" . nl2br(htmlspecialchars($row['Description'])) . "</td>"; # nl2br = creates display separation 
                        echo "<td class='duties'>" . nl2br(htmlspecialchars($row['Responsibilities & Requirements'])) . "</td>";
                        echo "</tr>";
                    }

                    echo "</tbody></table>";
                } else {
                    echo "<p>Database query could not be prepared.</p>";
                }

                mysqli_close($conn);

            ?>
        </section>

        <!-- Ordered list: Hiring process -->
        <section class="hiring-process" aria-labelledby="process-title">
            <h2 id="process-title">Our Hiring Process</h2>
            <ol>
                <li>Submit your application online</li>
                <li>Initial HR screening call</li>
                <li>Technical/creative interview</li>
                <li>Final team interview</li>
                <li>Receive your offer and join SDAJ!</li>
            </ol>
        </section>

        <!-- Application link -->
        <div class="application">
            <p><a href="apply.php" target="_blank">Apply Here</a></p>
        </div>
    </main>

    <!-- Footer -->
    <?php include 'inc_files/footer.inc'; ?>
    
    
</body>
</html>
