<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="Game Development Company">
        <meta name="keywords" content="company logo, name, slogan, description, image, menu, footer with Jira & Github link, email link">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>SDAJ Webpage</title>
        <link rel="stylesheet" href="styles/layout.css">
        <link rel="stylesheet" href="styles/colours.css">

        <style> /*Embedded CSS for image text hover*/
            .image_text:hover{
                background-color: #ff0000; 
                color: #0d0d0d;
            }

            .image_text a:hover{
                background-color: #ff0000; 
                color: #0d0d0d; 
            }

            .image_text:hover h1,
            .image_text:hover p {
                color: #0d0d0d; 
                transition: color 0.4s ease-in-out; /* reference the wesbite where you learned this */
            }

        </style>
    </head>
    
    <body>

         <header class="header-logo"> <!--Company logo in header-->
                <img src="images/SDAJ_logo.png" alt="company logo" style="width: 100px; height: auto;"> <!--logo reference - https://cooltext.com/Logo-Design-Fantasy-->
         </header>
    